version: '3.7'

services:
  db:
    env_file: ./.env 
    image: "redis:${REDIS_IMAGE_VERSION}"
    container_name: ${REDIS_CONTAINER_NAME}
    command: "redis-server --requirepass ${REDIS_ROOT_PASSWORD}"
    restart: always
    tty: true
    stdin_open: true
    ports: 
      - "${REDIS_PORT}:6379"
